version: "3.4"
services:
  db:
    container_name: mongodb
    image: mongo
    networks:
      - custBridge
    ports:
      - '27017:27017'
  dbql:
    container_name: mysqlserver
    image: mysql
    networks:
      - custBridge
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movieDb
      MYSQL_USER: root
      MYSQL_ROOT_HOST: "%"
  eureka:
    container_name: eurekaServer
    build: ./eureka-server/
    networks:
      - custBridge
    ports:
      - '8761:8761'
  config:
    container_name: configServer
    build: ./config-server/
    networks:
      - custBridge
    ports:
      - '8888:8888'
    environment:
      WAIT_HOSTS: eureka:8761
      WAIT_HOSTS_TIMEOUT: 100
  movie:
    container_name: movieService
    networks:
      - custBridge
    build: ./movie-service/
    ports:
      - '8081:8081'
    environment:
      WAIT_HOSTS: config:8888
      WAIT_HOSTS_TIMEOUT: 100
    links:
      - db:mongodb
  zuul:
    container_name: zuulGateway
    networks:
      - custBridge
    build: ./api-gateway/
    ports:
      - '8080:8080'
  user:
    container_name: userService
    build: ./user-service/
    networks:
      - custBridge
    ports:
      - '8082:8082'
    environment:
      WAIT_HOSTS: config:8888, dbql:3306, rabbitmq:5672
      WAIT_HOSTS_TIMEOUT: 100
    links:
      - dbql:mysqlserver
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit
    networks:
      - custBridge
    ports:
      - "5672:5672"
      - "15672:15672"
networks:
  custBridge:
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.0.0/16
